### PR TITLE
Added TranslateHeadless sample

### PR DESCRIPTION
**Pull request by RodgerLeblanc**

### CODE REVIEW

**Comment by jcmurray** [comment]
Nice code sample! I've seen this topic frequently raised on the forums and this example is a great demonstration of how it can be done.

**Comment by timwindsor** [comment]
I don't think subprojects work very well with GitHub. Can you remove it as a subproject and commit the files directly? You may need to remove the local .git folder and re-add the files, or something like that.

**Comment by RodgerLeblanc** [comment]
Ok, just forget about it, I've lost my whole evening yesterday to try to
add my project to Community Sample GitHub, it worked after 5 frustrating
hours and now I need to redo it?

I'll just keep it on my private GitHub and won't contribute until I get to
know more GitHub, as of right now, I'm just wasting my time and I have no
idea what you are talking about (remove subproject, commit files directly,
remove local .git folder, etc)


--
*Roger Leblanc*
CEO, CellNinja <http://appworld.blackberry.com/webstore/vendor/70290/>
Montreal BlackBerry Enterprise Developer Group Manager
m: +1 807 355 2627 | t: +1 819 840 9428 |
<http://twitter.com/RodgerLeblanc>

2015-05-21 14:38 GMT-04:00 Tim Windsor <notifications@github.com>:

**Comment by thurask** [comment]
Excuse me, but I think it's something like this:

1. Delete contents of TranslateHeadless folder within your copy of Cascades-Community-Samples
2. Copy entire contents of https://github.com/RodgerLeblanc/TranslateHeadless to within the TranslateHeadless folder, i.e.
Cascades-Community-Samples\TranslateHeadless\TranslateHL\...
Cascades-Community-Samples\TranslateHeadless\TranslateHLService\...
Cascades-Community-Samples\TranslateHeadless\LICENSE
Cascades-Community-Samples\TranslateHeadless\README.md
etc.
3. Commit these changes to your copy of Cascades-Community-Samples. It should automatically add to this pull request.

**Comment by timwindsor** [comment]
@RodgerLeblanc I'm very sorry that it's been such a pain to get this far. I would say the "learning curve" with Git/GitHub is steep, but sometimes it's more of a "punishment curve", and involves quasi-magical incantations to make it work properly. One of our top contributors pretty much refuses to deal with it and just has me commit stuff for him, so don't feel bad at all that this didn't work.

Do you think you'll be updating your sample much? If so, I can just enter in a Readme file instead that points to your project. If you're pretty much done with it though, I can grab the code and commit it into the repo and set you as the author, like I've done for some other committers.

Given the value of the sample and that people are asking about it, I'd like to do one or the other so that it's discoverable.

**Comment by RodgerLeblanc** [comment]
I won't update the sample, unless a dev finds an error with the code.I've tried to commit again using @Thurask instructions, if it didn't worked, you can commit to the repo yourself, I won't try a third time myself.Thanks!                                                                                                                                                                                                                                                                          --Roger LeblancCEO, CellNinjaMontreal BlackBerry Enterprise Developer Group Managerm: +1 807 355 2627 | t: +1 819 840 9428 | @RodgerLeblanc                                                                                                                                                                                                                From: Tim WindsorSent: Friday, May 22, 2015 1:48 PMTo: blackberry/Cascades-Community-SamplesReply To: blackberry/Cascades-Community-SamplesCc: Roger LeblancSubject: Re: [Cascades-Community-Samples] Added TranslateHeadless sample (#224)@RodgerLeblanc I'm very sorry that it's been such a pain to get this far. I would say the "learning curve" with Git/GitHub is steep, but sometimes it's more of a "punishment curve", and involves quasi-magical incantations to make it work properly. One of our top contributors pretty much refuses to deal with it and just has me commit stuff for him, so don't feel bad at all that this didn't work.

Do you think you'll be updating your sample much? If so, I can just enter in a Readme file instead that points to your project. If you're pretty much done with it though, I can grab the code and commit it into the repo and set you as the author, like I've done for some other committers.

Given the value of the sample and that people are asking about it, I'd like to do one or the other so that it's discoverable.

—Reply to this email directly or view it on GitHub.

**Comment by timwindsor** [comment]
Okay, I've merged in your sample now. Thanks for all the hard work on it, I think it will be of value to many.

@jcmurray John, would you be interested in doing a blog post on this contribution?

**Comment by jcmurray** [comment]
Happy to do a blog post on this contribution if it's ok with @RodgerLeblanc :-)

**Comment by RodgerLeblanc** [comment]
Sure!

**Comment by jcmurray** [comment]
Thanks. What contact details should I use for you in the post? I tend to use my Twitter handle but you can use whatever you're comfortable with being public.

**Comment by RodgerLeblanc** [comment]
@RodgerLeblanc

**Pull request closed without merging**
